name: CI
on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      - name: Run GUI
        run: |
          echo Hello, World!
          pip3 install -r requirements.txt --break-system-packages
          python3 app.py
    
